version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: 'dspider_zookeeper'
    volumes:
    - './bitnami/zookeeper:/bitnami/zookeeper:rw'
    environment:
      TZ: '$TZ'
      ZOO_ENABLE_AUTH: 'yes'
      ZOO_SERVER_USERS: 'kafka'
      ZOO_SERVER_PASSWORDS: 'BooSho2Yei8r'
      ZOO_CLIENT_USERS: 'kafka'
      ZOO_CLIENT_PASSWORD: 'BooSho2Yei8r'
    restart: 'always'
    networks:
      dspider:
        aliases:
        - 'zookeeper'
  kafka:
    image: 'bitnami/kafka:2.8.1'
    container_name: 'dspider_kafka'
    hostname: 'dspider_kafka'
    ports:
    - '9093:9093'
    volumes:
    - './bitnami/kafka:/bitnami/kafka:rw'
    - './certs/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
    - './certs/server.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    environment:
      TZ: '$TZ'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:SASL_SSL,CLIENT:SASL_SSL'
      KAFKA_CFG_LISTENERS: 'INTERNAL://:9092,CLIENT://:9093'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'INTERNAL://:9092,CLIENT://:9093'
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_BROKER_ID: '1'
      KAFKA_CFG_NUM_PARTITIONS: '10'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ZOOKEEPER_PROTOCOL: 'SASL'
      KAFKA_ZOOKEEPER_USER: 'kafka'
      KAFKA_ZOOKEEPER_PASSWORD: 'BooSho2Yei8r'
      KAFKA_INTER_BROKER_USER: 'dspider'
      KAFKA_INTER_BROKER_PASSWORD: 'agheLahb0eij'
      KAFKA_CLIENT_USERS: 'dspider'
      KAFKA_CLIENT_PASSWORDS: 'agheLahb0eij'
      KAFKA_TLS_TYPE: 'JKS'
      KAFKA_CERTIFICATE_PASSWORD: 'eeduuNguVah9'
    depends_on:
    - 'zookeeper'
    networks:
      dspider:
        aliases:
        - 'kafka'
  redis:
    image: 'redis:7.0.4'
    container_name: 'dspider_redis'
    ports:
    - '6379:6379'
    volumes:
    - './bitnami/redis:/data:rw'
    command:
    - 'redis-server'
    - '--appendonly'
    - 'yes'
    - '--requirepass'
    - 'Vah7ahWae1Ke'
    networks:
      dspider:
        aliases:
        - 'redis'
networks:
  dspider:
    name: 'dspider'
