# Generated by Django 4.1 on 2022-08-29 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('url', models.CharField(max_length=100, verbose_name='任务第一个请求的URL')),
                ('method', models.CharField(max_length=25, null=True, verbose_name='请求方法')),
                ('headers', models.TextField(null=True)),
                ('payload', models.TextField(null=True)),
                ('timeout', models.IntegerField(null=True)),
                ('use_robots', models.BooleanField(default=False)),
                ('use_tor', models.BooleanField(default=False)),
                ('use_proxy', models.BooleanField(default=False)),
                ('generator_id', models.CharField(max_length=32)),
                ('generator_cfg', models.TextField(null=True)),
                ('matcher_id', models.CharField(max_length=32)),
                ('matcher_cfg', models.TextField(null=True)),
                ('exporter_id', models.CharField(max_length=32)),
                ('exporter_cfg', models.TextField(null=True)),
                ('is_periodic', models.BooleanField(default=False)),
                ('task_status', models.SmallIntegerField(default=0)),
                ('cron_expn', models.CharField(max_length=60, null=True)),
                ('req_interval', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
