# Generated by Django 4.1 on 2022-08-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(help_text='用户ID', verbose_name='用户ID'),
        ),
    ]
