# Generated by Django 4.1 on 2022-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0002_alter_task_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(verbose_name='用户ID'),
        ),
    ]
