# Generated by Django 4.1 on 2022-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ds', '0006_pageuserpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='PageUserPermissions',
        ),
    ]
