# Generated by Django 4.1 on 2022-09-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0008_page_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='permissions',
            new_name='user_permissions',
        ),
    ]
