# Generated by Django 4.1 on 2022-09-15 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ds', '0009_rename_permissions_page_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('plugin_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('plugin_name', models.CharField(default='', max_length=50)),
                ('plugin_type', models.SmallIntegerField(default=0)),
                ('plugin_plain', models.TextField(default='', null=True)),
                ('code_obj', models.BinaryField()),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ds.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='user_permissions',
            field=models.ManyToManyField(related_name='pages', to='auth.permission'),
        ),
    ]
