# Generated by Django 4.1 on 2022-09-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0010_plugin_task_task_name_alter_page_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='plugin_id',
            new_name='id',
        ),
    ]
