# Generated by Django 4.1 on 2022-09-15 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0011_rename_plugin_id_plugin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_task_set', to='ds.plugin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='generator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_task_set', to='ds.plugin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='matcher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_task_set', to='ds.plugin'),
        ),
    ]
