# Generated by Django 4.1 on 2022-09-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0012_alter_task_exporter_id_alter_task_generator_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='exporter_id',
            new_name='exporter',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='generator_id',
            new_name='generator',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='matcher_id',
            new_name='matcher',
        ),
    ]
