# Generated by Django 4.1.1 on 2022-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0013_rename_exporter_id_task_exporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exporter_cfg',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='generator_cfg',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='headers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='matcher_cfg',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='payload',
            field=models.JSONField(null=True),
        ),
    ]
