# Generated by Django 4.1.1 on 2022-09-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0014_alter_task_exporter_cfg_alter_task_generator_cfg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exporter_cfg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='generator_cfg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='headers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='matcher_cfg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='payload',
            field=models.TextField(null=True),
        ),
    ]
