# Generated by Django 4.1.1 on 2022-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0015_alter_task_exporter_cfg_alter_task_generator_cfg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payload',
            field=models.BinaryField(null=True),
        ),
    ]
