# Generated by Django 4.1.1 on 2022-09-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0016_alter_task_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='code_obj_version',
            field=models.CharField(default='', max_length=32),
        ),
    ]
