# Generated by Django 4.1.1 on 2022-09-21 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0017_plugin_code_obj_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(default=0)),
                ('content', models.BinaryField(default=b'')),
                ('occur_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('plugin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_logs', to='ds.plugin')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='ds.task')),
            ],
        ),
    ]
