# Generated by Django 4.1.1 on 2022-09-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0018_pluginlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PluginLog',
            new_name='Log',
        ),
    ]
