# Generated by Django 4.1.1 on 2022-09-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0019_rename_pluginlog_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='plugin_id',
            new_name='plugin',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='task_id',
            new_name='task',
        ),
    ]
