# Generated by Django 4.1.1 on 2022-09-23 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ds', '0020_rename_plugin_id_log_plugin_rename_task_id_log_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cron_expn',
        ),
        migrations.RemoveField(
            model_name='task',
            name='exporter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='exporter_cfg',
        ),
        migrations.RemoveField(
            model_name='task',
            name='generator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='generator_cfg',
        ),
        migrations.RemoveField(
            model_name='task',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_periodic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='matcher',
        ),
        migrations.RemoveField(
            model_name='task',
            name='matcher_cfg',
        ),
        migrations.RemoveField(
            model_name='task',
            name='method',
        ),
        migrations.RemoveField(
            model_name='task',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='task',
            name='req_interval',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='task',
            name='url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='use_proxy',
        ),
        migrations.RemoveField(
            model_name='task',
            name='use_robots',
        ),
        migrations.RemoveField(
            model_name='task',
            name='use_tor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reqs_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='results_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='total_reqs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='total_results',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=25, null=True)),
                ('headers', models.TextField(null=True)),
                ('payload', models.BinaryField(null=True)),
                ('timeout', models.IntegerField(null=True)),
                ('use_robots', models.BooleanField(default=False)),
                ('use_tor', models.BooleanField(default=False)),
                ('use_proxy', models.BooleanField(default=False)),
                ('generator_cfg', models.TextField(default='{}', null=True)),
                ('matcher_cfg', models.TextField(default='{}')),
                ('exporter_cfg', models.TextField(default='{}')),
                ('is_periodic', models.BooleanField(default=False)),
                ('plan_status', models.SmallIntegerField(default=0)),
                ('cron_expn', models.CharField(max_length=60, null=True)),
                ('req_interval', models.IntegerField(default=5, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_plan_set', to='ds.plugin')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_plan_set', to='ds.plugin')),
                ('matcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_plan_set', to='ds.plugin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ds.plan'),
        ),
    ]
