# Generated by Django 4.1.1 on 2022-09-23 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0022_alter_task_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_logs', to='ds.plugin'),
        ),
        migrations.AlterField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_logs', to='ds.task'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='exporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_plans', to='ds.plugin'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_plans', to='ds.plugin'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='matcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_plans', to='ds.plugin'),
        ),
    ]
