# Generated by Django 4.1.1 on 2022-09-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0023_alter_log_plugin_alter_log_task_alter_plan_exporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
