# Generated by Django 4.1.1 on 2022-09-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0024_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='total_reqs',
            field=models.IntegerField(default=1),
        ),
    ]
